### ISSUE TITLE
406 Client Error: Not Acceptable for url: http://127.0.0.1:9200/git_enrich/_search

### ISSUE THREAD

**Issue by innovationchef** [chaoss/grimoirelab-manuscripts#16] opened 2018-02-17 20:34 UTC
I am trying to run the sample report generation example given in the documentation. I followed the following sequence of commands - 
`$ p2o.py --enrich --index git_raw --index-enrich git -e http://127.0.0.1:9200 --no_inc --debug git https://github.com/grimoirelab/perceval.git`
`$ p2o.py --enrich --index git_raw --index-enrich git -e http://127.0.0.1:9200 --no_inc --debug git https://github.com/grimoirelab/GrimoireELK.git`
`$ kidash --elastic_url-enrich http://127.0.0.1:9200 --import /tmp/git-dashboard.json`
The dashboard is successfully created. Next, I tried to generate the manuscripts using the following - 
`$ manuscripts -g -d /tmp/reports -u http://127.0.0.1:9200 -n GrimoireLab --data-sources git`
which throws the Client Error. I figured out that the url is not created and that is why manuscript command throws this error.

http://127.0.0.1:9200                                   is fine
http://127.0.0.1:9200/git_raw?pretty=true   is also fine
http://127.0.0.1:9200/git_enrich/_search    but this throws Error 404 

This means that the enrich_backend function is not creating this url. But, I further investigated and found that the `enrich_backend(args)` function in arthur.py (through p2o.py) is working fine as it logs the following in terminal - "Enrich backend completed"

**Comment by jgbarah** [comment] 2018-02-18 20:02
Hi, @innovationchef. Thanks for the report. In this case, what happens is that Manuscripts expected the git enriched index to be `git_enriched`, but when running `p2o.py` you are creating it as `git` (have a look at the `--index-enrich` option in `p2o.py`).

I'm trying to make this more clear in the tutorial, and maybe file an issue in Manuscripts, since AFAIK, the default enriched index for git is `git`, anyway.

To make Manuscripts work, please re-run `p2o.py` with `--index enrich git_enrich`, or create an alias in Elasticsearch for `git_enrich`, pointing to `git`.

Please, let me know if any of these worked, so that we can close this issue.

**Comment by innovationchef** [comment] 2018-02-19 06:20
Hi @jgbarah ,
Your solution worked partially. Now my link http://127.0.0.1:9200/git_enrich/_search is working fine. But, the manuscripts throws the same error. 

Additionally, I have got 1 more issue. For some reasons, I reinstalled the whole system yesterday. The p2o.py command and the kidash command to generate dashboards are working fine. But at http://127.0.0.1:5601 , **everytime** I click on the dashboard tab, it asks me to "create an index pattern to retrieve data from Elasticsearch" (I don't remember if I got this option in my first installation), **even when I configured it once.**

**Comment by innovationchef** [comment] 2018-02-20 23:29
Hi @jgbarah ,
I dug deeper into the issue and reached to grimoirelab-manuscripts/manuscrpits/metrics/metrics.py line 140
`r = requests.post(url,query)`
where `url = http://localhost:9200/git_enrich/_search`
and `query = some_json` (attached in screenshot)

`r.raise_for_status()` is raising status error because the cardinality aggregation problem. The 'field' value should not be set "None". 

I ran a sample query from the manuscripts output on Kibana console and got this error -  
```
{
  "error": {
    "root_cause": [
      {
        "type": "json_parse_exception",
        "reason": "Unrecognized token 'None': was expecting 'null', 'true', 'false' or NaN\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@166bf516; line: 27, column: 33]"
      }
    ],
    "type": "json_parse_exception",
    "reason": "Unrecognized token 'None': was expecting 'null', 'true', 'false' or NaN\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@166bf516; line: 27, column: 33]"
  },
  "status": 500
}
```
I am attaching ascreenshot as well. 
![screenshot from 2018-02-21 04-57-31](https://user-images.githubusercontent.com/18079078/36454928-fe2da358-16c3-11e8-8b06-44dbd57670e9.png)

**Comment by innovationchef** [comment] 2018-02-20 23:42
Hi @jgbarah ,
I dug deeper into the issue and reached to grimoirelab-manuscripts/manuscrpits/metrics/metrics.py line 140
`r = requests.post(url,query)`
where `url = http://localhost:9200/git_enrich/_search`
and `query = some_json` (attached in screenshot)

`r.raise_for_status()` is raising status error because the cardinality aggregation problem. The 'field' value should not be set "None". But in the current code, `FIELD_COUNT = None` is declared

I ran a sample query from the manuscripts output on Kibana console and got this error -  
```
{
  "error": {
    "root_cause": [
      {
        "type": "json_parse_exception",
        "reason": "Unrecognized token 'None': was expecting 'null', 'true', 'false' or NaN\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@166bf516; line: 27, column: 33]"
      }
    ],
    "type": "json_parse_exception",
    "reason": "Unrecognized token 'None': was expecting 'null', 'true', 'false' or NaN\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@166bf516; line: 27, column: 33]"
  },
  "status": 500
}
```
I am attaching a screenshot as well. 
![screenshot from 2018-02-21 04-57-31](https://user-images.githubusercontent.com/18079078/36454928-fe2da358-16c3-11e8-8b06-44dbd57670e9.png)

NOTE: The query that I used to produce this error was generated by the metrics.py file following the examples in the document.

Can you suggest something for this?

**Comment by aswanipranjal** [comment] 2018-02-25 11:05
hey @jgbarah, I too was having the same problem. I am using Elasticsearch-6  and I was getting a 406 error because the `Content-Type` header wasn't set in the request that is being made in `get_metrics_data` function in [metrics.py](https://github.com/chaoss/grimoirelab-manuscripts/blob/master/manuscripts/metrics/metrics.py) file on line 137. According to [this](https://www.elastic.co/blog/strict-content-type-checking-for-elasticsearch-rest-requests) article,  since the release of Elasticsearch-6, strict Content-Type headers are required to make a request to an elasticsearch instance.

It can be solved by adding headers in `get_metrics_data` function, like this (on line 137 of [metrics.py](https://github.com/chaoss/grimoirelab-manuscripts/blob/master/manuscripts/metrics/metrics.py)) :
```
es_headers = {'Content-Type':'application/json'}
r = requests.post(url, data=query, headers=es_headers)
```

can you please look into this?
Thanks!

**Comment by jgbarah** [comment] 2018-02-25 22:12
Ooops. Sorry for not coming back before. I was trying to reproduce the problem, and I couldn't. Until I realized maybe it was a problem with the Elasticsearch version. So, I tried with Elasticsearch 6.1, and it didn't work, Same error as you had. Bingo!

The problem seems to be that some changes in queries for Elaticsearch 6.x are biting us. We were using Manuscripts only with Elasticsearch 5.x, and I handn't notices about the problem.

So, I'm tagging this a bug. We need to fix Manuscripts for Elasticsearch 6.x.

Meanwhile, for GSoC, please use Elasticsearch 5.x, and let me know if you find any problem. I hope you don't ... ;-)

**Comment by jgbarah** [comment] 2018-02-25 22:38
@aswanipranjal I had missed your comment. I will have a look into it, may it is just that. Thanks!

[If you already tested, that, please start a pull request!]

**Closed** 2018-03-01 19:26 UTC
Labels: bug
